import type { AircraftMetadata } from "@/lib/aircraft/types";
import type { AircraftMetadataProvider } from "@/lib/server/provider";

type Tar1090DatabaseBlock = Record<string, unknown>;
type Tar1090DatabaseRecord = unknown[];
const DATABASE_FOLDER_TTL_MS = 15 * 60_000;

function endpoint(baseUrl: string, path: string): string {
  const base = baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`;
  return new URL(path.replace(/^\//, ""), base).toString();
}

function validHex(value: string): string | null {
  const normalized = value.trim().toUpperCase();
  return /^[0-9A-F]{6}$/.test(normalized) ? normalized : null;
}

function validDatabaseFolder(value: string): string | null {
  const normalized = value.trim();
  return /^[A-Za-z0-9_-]+$/.test(normalized) ? normalized : null;
}

function stringValue(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const normalized = value.trim();
  return normalized ? normalized : null;
}

function databaseRecord(value: unknown): Tar1090DatabaseRecord | null {
  return Array.isArray(value) ? value : null;
}

/**
 * Reads the compressed, browser-oriented database generated by tar1090-db.
 * The files are served as gzip-encoded JSON by the tar1090 web root, which
 * Node's fetch transparently decompresses.
 */
export class Tar1090DbProvider implements AircraftMetadataProvider {
  readonly name = "tar1090-db";
  private databaseFolder: string | null | undefined;
  private databaseFolderExpiresAt = 0;
  private databaseFolderRequest: Promise<string | null> | null = null;
  private readonly blockCache = new Map<string, Promise<Tar1090DatabaseBlock | null>>();

  constructor(private readonly baseUrl: string) {}

  async getMetadata(icaoHex: string): Promise<AircraftMetadata | null> {
    const hex = validHex(icaoHex);
    if (!hex) return null;

    const folder = await this.getDatabaseFolder();
    if (!folder) return null;

    const record = await this.lookup(folder, hex);
    if (!record) return null;

    const registration = stringValue(record[0]);
    const icaoTypeCode = stringValue(record[1]);
    const aircraftDescription = stringValue(record[3]);
    if (!registration && !icaoTypeCode && !aircraftDescription) return null;

    return {
      registration,
      registrationCountry: null,
      registrationCountryCode: null,
      aircraftType: icaoTypeCode,
      icaoTypeCode,
      aircraftDescription,
      operator: null,
      manufacturer: null,
      source: this.name,
      retrievedAt: new Date().toISOString(),
    };
  }

  private async getDatabaseFolder(): Promise<string | null> {
    if (this.databaseFolder !== undefined && this.databaseFolderExpiresAt > Date.now()) return this.databaseFolder;
    if (this.databaseFolderRequest) return this.databaseFolderRequest;

    this.databaseFolderRequest = this.fetchDatabaseFolder()
      .catch(() => null)
      .then((folder) => {
        this.databaseFolder = folder;
        this.databaseFolderExpiresAt = Date.now() + DATABASE_FOLDER_TTL_MS;
        return folder;
      })
      .finally(() => {
        this.databaseFolderRequest = null;
      });
    return this.databaseFolderRequest;
  }

  private async fetchDatabaseFolder(): Promise<string | null> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2500);
    try {
      const response = await fetch(endpoint(this.baseUrl, ""), { cache: "no-store", signal: controller.signal });
      if (!response.ok) return null;
      const html = await response.text();
      const match = html.match(/\bdatabaseFolder\s*=\s*["']([^"']+)["']/);
      return match ? validDatabaseFolder(match[1]) : null;
    } finally {
      clearTimeout(timeout);
    }
  }

  private loadBlock(folder: string, blockKey: string): Promise<Tar1090DatabaseBlock | null> {
    const cacheKey = `${folder}/${blockKey}`;
    const cached = this.blockCache.get(cacheKey);
    if (cached) return cached;

    const request = this.fetchBlock(folder, blockKey).catch(() => null);
    this.blockCache.set(cacheKey, request);
    return request;
  }

  private async fetchBlock(folder: string, blockKey: string): Promise<Tar1090DatabaseBlock | null> {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 2500);
    try {
      const response = await fetch(endpoint(this.baseUrl, `${folder}/${blockKey}.js`), {
        cache: "no-store",
        signal: controller.signal,
      });
      if (!response.ok) return null;
      const payload: unknown = await response.json();
      return payload && typeof payload === "object" && !Array.isArray(payload)
        ? payload as Tar1090DatabaseBlock
        : null;
    } finally {
      clearTimeout(timeout);
    }
  }

  private async lookup(folder: string, hex: string): Promise<Tar1090DatabaseRecord | null> {
    for (let level = 1; level <= hex.length; level += 1) {
      const blockKey = hex.slice(0, level);
      const block = await this.loadBlock(folder, blockKey);
      if (!block) return null;

      const suffix = hex.slice(level);
      const direct = databaseRecord(block[suffix]);
      if (direct) return direct;

      const children = Array.isArray(block.children) ? block.children : [];
      const childKey = `${blockKey}${suffix.slice(0, 1)}`;
      if (!children.some((child) => child === childKey)) return null;
    }
    return null;
  }
}
