"use client";

import { useEffect, useState } from "react";

type Fleet = { id: string; name: string; description?: string; enabled: boolean; matchers: { id: string; type: string; value: string }[] };
type Geofence = { id: string; name: string; centerLat: number; centerLon: number; radiusMeters: number; enabled: boolean };
type Rule = { id: string; name: string; enabled: boolean; trigger: string; target: { kind: string; fleetId?: string }; channels: string[] };

export function AlertsAdminPage() {
  const [fleets, setFleets] = useState<Fleet[]>([]); const [geofences, setGeofences] = useState<Geofence[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [name, setName] = useState(""); const [geoName, setGeoName] = useState(""); const [message, setMessage] = useState("");
  const reload = async () => { const [fleetResponse, ruleResponse] = await Promise.all([fetch("/api/admin/alerts/fleets", { cache: "no-store" }), fetch("/api/admin/alerts/rules", { cache: "no-store" })]); if (fleetResponse.ok) setFleets((await fleetResponse.json()).fleets); if (ruleResponse.ok) { const data = await ruleResponse.json(); setRules(data.rules); setGeofences(data.geofences); } };
  useEffect(() => { void reload(); }, []);
  async function createFleet(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/alerts/fleets", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }); setMessage(response.ok ? "Fleet saved" : "Fleet could not be saved"); setName(""); if (response.ok) void reload(); }
  async function createGeofence(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/admin/alerts/geofences", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: geoName, centerLat: 49.2, centerLon: 16.6, radiusMeters: 40000 }) }); setMessage(response.ok ? "Geofence saved" : "Geofence could not be saved"); setGeoName(""); if (response.ok) void reload(); }
  async function toggleFleet(fleet: Fleet) { await fetch(`/api/admin/alerts/fleets/${fleet.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: !fleet.enabled }) }); void reload(); }
  return <main className="history-page"><header className="history-page-header"><div><h1>Alerts & fleets</h1><p className="statistics-subtitle">Durable alert configuration and delivery audit.</p></div></header><p role="status">{message}</p><div className="statistics-grid"><section className="statistics-card"><h2>Fleets</h2><form onSubmit={createFleet} className="watchlist-editor-form"><label>Name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><button className="primary-button" type="submit">Create fleet</button></form><ul>{fleets.map((fleet) => <li key={fleet.id}><strong>{fleet.name}</strong> <button className="secondary-button" type="button" onClick={() => toggleFleet(fleet)}>{fleet.enabled ? "Disable" : "Enable"}</button></li>)}</ul></section><section className="statistics-card"><h2>Geofences</h2><form onSubmit={createGeofence} className="watchlist-editor-form"><label>Name<input value={geoName} onChange={(event) => setGeoName(event.target.value)} required /></label><small>Initial center: safe product default (49.2, 16.6), radius 40 km.</small><button className="primary-button" type="submit">Create geofence</button></form><ul>{geofences.map((geo) => <li key={geo.id}><strong>{geo.name}</strong> · {Math.round(geo.radiusMeters / 1000)} km</li>)}</ul></section><section className="statistics-card"><h2>Rules</h2>{rules.length ? <ul>{rules.map((rule) => <li key={rule.id}><strong>{rule.name}</strong> · {rule.trigger} · {rule.channels.join(", ")}</li>)}</ul> : <p>No durable rules configured.</p>}</section></div></main>;
}
