"use client";
import { ATC_SECTOR_STACKS } from "@/lib/atc-sector-stacks";
import { useSearchParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { historyWindow, SECTOR_HISTORY_BUCKET, type SectorHistoryMetric, type SectorHistoryRange, type SectorTrafficHistoryBatch } from "@/lib/atc-sector-history";

export interface SectorTrafficPanelItem { sectorId: string; name: string; vertical: { lower: string | null; upper: string | null }; traffic: { aircraftCount: number }; trafficLevel: string; }
export interface SectorFlow { fromSectorId: string; toSectorId: string; count: number; }

function HistoryChart({ sectors, metric }: { sectors: SectorTrafficHistoryBatch["sectors"]; metric: SectorHistoryMetric }) {
  const width = 640; const height = 180; const all = sectors.flatMap((s) => s.points.map((p) => p[metric])).filter((v): v is number => v !== null); const max = Math.max(1, ...all); const min = Math.min(0, ...all); const x = (i: number, n: number) => n <= 1 ? 0 : (i / (n - 1)) * width; const y = (v: number) => height - ((v - min) / (max - min || 1)) * (height - 12);
  return <svg className="atc-history-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Traffic history chart">{sectors.map((sector, si) => { const segments: string[] = []; let current = ""; sector.points.forEach((point, i) => { const value = point[metric]; if (value === null) { if (current) segments.push(current); current = ""; } else current += `${current ? "L" : "M"}${x(i, sector.points.length)} ${y(value)} `; }); if (current) segments.push(current); return <g key={sector.sectorId} className={`atc-history-series atc-history-series-${si}`}>{segments.map((path, i) => <path key={i} d={path} fill="none" />)}</g>; })}</svg>;
}

function TrafficHistory({ sectorIds, compare = false, onClose }: { sectorIds: string[]; compare?: boolean; onClose?: () => void }) {
  const searchParams = useSearchParams(); const [range, setRange] = useState<SectorHistoryRange>("24h"); const [metric, setMetric] = useState<SectorHistoryMetric>("aircraftCount"); const [state, setState] = useState<"idle" | "loading" | "data" | "empty" | "error">("idle"); const [data, setData] = useState<SectorTrafficHistoryBatch | null>(null);
  const effectiveAt = useMemo(() => { const value = searchParams.get("at"); const parsed = value ? new Date(value) : new Date(); return Number.isFinite(parsed.getTime()) ? parsed : new Date(); }, [searchParams]);
  useEffect(() => { const controller = new AbortController(); const { from, to } = historyWindow(range, effectiveAt); setState("loading"); const ids = sectorIds.join(","); const url = compare ? `/api/atc/sectors/history?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}&bucket=${SECTOR_HISTORY_BUCKET[range]}&sectors=${encodeURIComponent(ids)}` : `/api/atc/sectors/${encodeURIComponent(sectorIds[0])}/history?from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}&bucket=${SECTOR_HISTORY_BUCKET[range]}`; fetch(url, { cache: "no-store", signal: controller.signal }).then(async (response) => { if (!response.ok) throw new Error("history unavailable"); const payload = await response.json(); const normalized = compare ? payload as SectorTrafficHistoryBatch : { ...payload, sectors: [payload] } as SectorTrafficHistoryBatch; setData(normalized); setState(normalized.sectors.some((s) => s.points.length) ? "data" : "empty"); }).catch((error) => { if (!(error instanceof DOMException && error.name === "AbortError")) setState("error"); }); return () => controller.abort(); }, [compare, effectiveAt, range, sectorIds]);
  const first = data?.sectors[0]; const coverage = (data as (SectorTrafficHistoryBatch & { coverage?: { complete: boolean } }) | null)?.coverage; return <details className="atc-history" open><summary>Traffic history</summary><div className="atc-history-controls"><span>{(["1h", "6h", "24h", "7d"] as SectorHistoryRange[]).map((value) => <button key={value} type="button" aria-pressed={range === value} onClick={() => setRange(value)}>{value}</button>)}</span><label>Metric <select value={metric} onChange={(event) => setMetric(event.target.value as SectorHistoryMetric)}><option value="aircraftCount">Aircraft</option><option value="entering">Entries</option><option value="leaving">Exits</option><option value="averageAltitude">Average altitude</option><option value="averageGroundSpeed">Average speed</option></select></label>{onClose && <button type="button" onClick={onClose}>Close</button>}</div>{state === "loading" && <small>Loading history…</small>}{state === "error" && <small>History unavailable.</small>}{state === "empty" && <small>No retained observations in this interval.</small>}{coverage && !coverage.complete && <p role="status">History is incomplete because the requested interval exceeds the current processing limit. Summary values are incomplete.</p>}{data && state === "data" && <><HistoryChart sectors={data.sectors} metric={metric} /><div className="atc-history-summary">{first && !compare && <><span><b>Peak</b> {first.peakAircraftCount} · {first.peakAircraftAt ? new Date(first.peakAircraftAt).toISOString() : "No data"}</span><span><b>Average</b> {first.averageAircraftCount}</span><span><b>Entries</b> {first.totalEntries}</span><span><b>Exits</b> {first.totalExits}</span></>}{compare && <span>{data.sectors.map((s) => `${s.name ?? s.sectorId}: ${s.peakAircraftCount}`).join(" · ")}</span>}</div></>}<small>Statistics reflect aircraft observed by AirRadar and depend on ADS-B coverage and retained FlightPosition data.</small></details>;
}

export function AtcVerticalTraffic({ traffic }: { traffic: Map<string, SectorTrafficPanelItem> }) {
  const [history, setHistory] = useState<string[] | null>(null); return <details className="map-overlay-card atc-traffic-panel"><summary>ATC Vertical Traffic</summary>{ATC_SECTOR_STACKS.map((stack) => <section key={stack.id}><strong>{stack.label}</strong>{stack.members.map((id) => { const item = traffic.get(id); return <div key={id} className="atc-stack-row"><b>{item?.name ?? id}</b><span>{item ? `${item.vertical.lower ?? "—"}–${item.vertical.upper ?? "—"}` : "NO DATA"}</span><span>{item ? `${item.traffic.aircraftCount} aircraft · ${item.trafficLevel}` : "NO DATA"}</span></div>; })}{stack.id === "SOUTH" && <button type="button" onClick={() => setHistory(["LKAATB", "LKAANSL", "LKAAS"])}>Show history</button>}</section>)}<small>Published sector volumes only. Does not indicate official ATC sector activation.</small>{history && <><TrafficHistory sectorIds={history} compare onClose={() => setHistory(null)} /><small>Shows aircraft observed within the published SOUTH sector volumes. Does not represent the operational ATC sector configuration.</small></>}</details>;
}

export function SectorTrafficHistoryPanel({ sectorId }: { sectorId: string }) { return <TrafficHistory sectorIds={[sectorId]} />; }

export function SectorFlowsPanel({ flows, windowMinutes, onWindowChange }: { flows: SectorFlow[]; windowMinutes: 1 | 5 | 15; onWindowChange: (value: 1 | 5 | 15) => void }) {
  return <details className="map-overlay-card atc-traffic-panel"><summary>Sector flows · {windowMinutes}m</summary><div className="atc-flow-buttons">{([1, 5, 15] as const).map((value) => <button key={value} type="button" aria-pressed={value === windowMinutes} onClick={() => onWindowChange(value)}>{value}m</button>)}</div>{flows.length ? flows.map((flow) => <div key={`${flow.fromSectorId}-${flow.toSectorId}`} className="atc-stack-row"><b>{flow.fromSectorId.replace("LKAA", "")} → {flow.toSectorId.replace("LKAA", "")}</b><span>{flow.count}</span></div>) : <small>No sector transitions in this interval</small>}<small>Flows represent aircraft movement between published ATC sector volumes, not confirmed ATC handoffs.</small></details>;
}
