/* Diagnostic-only audit; never imported by AirRadar runtime code. */
import "dotenv/config";
import { writeFile } from "node:fs/promises";
type R = Record<string, unknown>;
const key = process.env.FLIGHTAWARE_API_KEY;
const base = (process.env.AIRRADAR_BASE_URL ?? "http://127.0.0.1:3000").replace(/\/$/, "");
const limit = Math.min(20, Math.max(1, Number(process.env.FLIGHTAWARE_AUDIT_LIMIT ?? 20)));
const delayMs = Math.max(0, Number(process.env.FLIGHTAWARE_AUDIT_DELAY_MS ?? 7500));
const decode = process.env.FLIGHTAWARE_AUDIT_DECODED_ROUTE === "1";
const counters = { flight: 0, route: 0, other: 0, rateLimited: 0 }; let lastRequest = 0;
const sleep = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));
const str = (v: unknown): string | null => typeof v === "string" && v.trim() ? v.trim() : null;
const rec = (v: unknown): R => v && typeof v === "object" ? v as R : {};
const code = (v: unknown): string | null => typeof v === "string" ? v.toUpperCase() : str(rec(v).code_icao) ?? str(rec(v).icao);
const status = (f: R): string => str(f.status) ?? "unknown";
const dates = (f: R) => [f.scheduled_off, f.estimated_off, f.actual_off, f.scheduled_on, f.estimated_on, f.actual_on].map((v) => Date.parse(String(v ?? ""))).filter(Number.isFinite);
function score(f: R, a: R): R { let n = 0; const why: string[] = []; const ar = rec(rec(a.enrichment).route); const ao = code(ar.origin), ad = code(ar.destination); if (ao && code(f.origin) === ao) { n += 40; why.push("origin exact"); } if (ad && code(f.destination) === ad) { n += 40; why.push("destination exact"); } if (str(a.registration) && str(f.registration)?.toUpperCase() === str(a.registration)?.toUpperCase()) { n += 20; why.push("registration exact"); } if (f.actual_off) { n += 30; why.push("departed"); } if (f.actual_off && !f.actual_on) { n += 25; why.push("not landed"); } if (/en route|airborne|active|in progress|departed/i.test(status(f))) { n += 30; why.push("active status"); } const ts = dates(f), now = Date.now(); if (ts.some((x) => x <= now && x >= now - 24 * 3600000)) { n += 20; why.push("time relevant"); } if (/scheduled|filed/i.test(status(f)) && !f.actual_off && a.onGround === false) { n -= 50; why.push("scheduled while airborne"); } if (f.actual_on) { n -= 60; why.push("already landed"); } if (ts.length && Math.min(...ts) > now + 6 * 3600000) { n -= 40; why.push("future"); } return { ...f, _score: n, _reason: why.join(", ") || "ident/time fallback" }; }
function route(value: unknown): R { const text = str(value); if (!text) return { classification: "NO_ROUTE", text: null, tokenCount: 0, tokens: [] }; const tokens = text.split(/\s+/).filter(Boolean); const detailed = tokens.length > 2 && tokens.some((x) => /^(DCT|[A-Z]\d{2,4})$/.test(x) || /^[A-Z]{4,5}$/.test(x)); return { classification: detailed ? "ROUTE_TEXT_DETAILED" : "ROUTE_TEXT", text, tokenCount: tokens.length, tokens }; }
function flight(f: R): R { return { id: str(f.fa_flight_id), ident: str(f.ident), identIcao: str(f.ident_icao), identIata: str(f.ident_iata), origin: code(f.origin), destination: code(f.destination), registration: str(f.registration), status: status(f), scheduledOff: str(f.scheduled_off), estimatedOff: str(f.estimated_off), actualOff: str(f.actual_off), scheduledOn: str(f.scheduled_on), estimatedOn: str(f.estimated_on), actualOn: str(f.actual_on), route: str(f.route), routeDistance: f.route_distance ?? null, filedAltitude: f.filed_altitude ?? null, filedAirspeed: f.filed_airspeed ?? null }; }
async function request(url: string, kind: "flight" | "route"): Promise<{ status: number; body: R | null }> { const wait = lastRequest + delayMs - Date.now(); if (wait > 0) await sleep(wait); lastRequest = Date.now(); counters[kind]++; const res = await fetch(url, { signal: AbortSignal.timeout(15000), headers: { Accept: "application/json", "x-apikey": key! } }); let body: R | null = null; try { body = await res.json() as R; } catch { /* empty */ } if (res.status === 429) { counters.rateLimited++; const retry = Number(res.headers.get("retry-after")); await sleep(Math.min(Math.max(Number.isFinite(retry) ? retry * 1000 : delayMs * 2, 1000), 120000)); } return { status: res.status, body }; }
const error = (s: number) => s === 429 ? "RATE_LIMITED" : `HTTP_${s}`;
if (!key) { console.error("FLIGHTAWARE_API_KEY is not set; no FlightAware request was made."); process.exitCode = 2; }
else {
  const local = await fetch(`${base}/api/aircraft?coverage=local`).then(async (r) => ({ status: r.status, body: await r.json() as R })); if (local.status !== 200 || !Array.isArray(local.body.aircraft)) throw new Error(`AirRadar snapshot unavailable: HTTP ${local.status}`);
  const aircraft = local.body.aircraft.filter((a): a is R => Boolean(a && typeof a === "object" && str(rec(a).callsign) && rec(a).onGround !== true && rec(a).lat != null)).filter((a, i, all) => all.findIndex((x) => str(x.callsign)?.replace(/\s/g, "").toUpperCase() === str(a.callsign)?.replace(/\s/g, "").toUpperCase()) === i).slice(0, limit); const rows: R[] = [];
  for (const a of aircraft) { const ident = str(a.callsign)!.replace(/\s+/g, "").toUpperCase(); const q = await request(`https://aeroapi.flightaware.com/aeroapi/flights/${encodeURIComponent(ident)}?max_pages=1`, "flight"); if (q.status !== 200 || !q.body) { rows.push({ ident, hex: a.icaoHex, result: error(q.status), error: error(q.status) }); continue; } const list = Array.isArray(q.body.flights) ? q.body.flights.filter((x): x is R => Boolean(x && typeof x === "object")).map((x) => score(x, a)).sort((x, y) => Number(y._score) - Number(x._score)) : []; const chosen = list[0]; const gap = chosen && list[1] ? Number(chosen._score) - Number(list[1]._score) : 99; const conf = chosen && Number(chosen._score) >= 45 && gap >= 8 ? (Number(chosen._score) >= 90 && gap >= 15 ? "high" : "medium") : "low"; const ambiguous = !chosen || conf === "low"; let decoded: R | null = null; if (decode && chosen?.fa_flight_id) { const d = await request(`https://aeroapi.flightaware.com/aeroapi/flights/${encodeURIComponent(String(chosen.fa_flight_id))}/route`, "route"); decoded = { status: d.status, error: d.status === 200 ? null : error(d.status) }; } const ar = rec(rec(a.enrichment).route); const routeInfo = route(chosen?.route); rows.push({ ident, hex: a.icaoHex, airradar: { origin: code(ar.origin), destination: code(ar.destination), registration: a.registration ?? null, lat: a.lat, lon: a.lon, track: a.track }, flightAware: chosen ? flight(chosen) : null, match: { candidateCount: list.length, score: chosen?._score ?? null, confidence: conf, reason: chosen?._reason ?? "no candidate" }, route: routeInfo, decodedRoute: decoded, candidates: ambiguous ? list.slice(0, 5).map((x) => ({ id: str(x.fa_flight_id), origin: code(x.origin), destination: code(x.destination), status: status(x), actualOff: str(x.actual_off), actualOn: str(x.actual_on), score: x._score })) : undefined, result: ambiguous ? "AMBIGUOUS_MATCH" : routeInfo.classification, error: null }); }
  const matched = rows.filter((r) => rec(r.match).confidence !== "low"); const detailed = matched.filter((r) => rec(r.route).classification === "ROUTE_TEXT_DETAILED"); const present = matched.filter((r) => rec(r.route).classification !== "NO_ROUTE"); const field = (x: string) => matched.filter((r) => rec(r.flightAware)[x] !== null && rec(r.flightAware)[x] !== undefined).length; const report = { generatedAt: new Date().toISOString(), tested: rows.length, matched: matched.length, detailed: detailed.length, coverageAll: rows.length ? detailed.length / rows.length : 0, coverageMatched: matched.length ? detailed.length / matched.length : 0, filed: { altitude: field("filedAltitude"), airspeed: field("filedAirspeed"), routeDistance: field("routeDistance") }, counters, rows }; await writeFile("flightaware-route-audit.json", JSON.stringify(report, null, 2), { mode: 0o600 }); console.log(`FlightAware textual-route audit\n================================\nTested aircraft: ${rows.length}\nFlightAware lookup successful: ${rows.filter((r) => r.error === null).length}/${rows.length}\nConfident flight matches: ${matched.length}/${rows.length}\nRoute text present: ${present.length}/${matched.length}\nDetailed route text: ${detailed.length}/${matched.length}\nDetailed route coverage among all: ${(report.coverageAll * 100).toFixed(1)}%\nDetailed route coverage among confident matches: ${(report.coverageMatched * 100).toFixed(1)}%\nFiled altitude available: ${report.filed.altitude}/${matched.length}\nFiled airspeed available: ${report.filed.airspeed}/${matched.length}\nRoute distance available: ${report.filed.routeDistance}/${matched.length}\nFlight lookup requests: ${counters.flight}\nDecoded route requests: ${counters.route}\nRate limited requests: ${counters.rateLimited}\nReport: flightaware-route-audit.json`);
}
