/* eslint-disable @typescript-eslint/no-explicit-any -- the read-only report adapts generated contract rows at runtime. */
import { mkdir, writeFile } from "node:fs/promises";
import { getPrisma } from "@/lib/server/db";
import { classifyTerminalGroundTruth, type TerminalTrackSample } from "@/lib/predictive-intelligence/terminal-ground-truth";
import { scoreEta, scoreRunway, summarizeEta, type EtaValidationResult, type GroundTruthStatus, type RunwayValidationResult } from "@/lib/predictive-intelligence/validation";

const jsonPath = process.env.PREDICTIVE_PROSPECTIVE_JSON ?? "artifacts/predictive-validation-prospective-v2.json";
const markdownPath = process.env.PREDICTIVE_PROSPECTIVE_MARKDOWN ?? "artifacts/predictive-validation-prospective-v2.md";
const MAX_OBSERVATIONS = 50_000;
type AnyTable = { all: () => Promise<any[]>; where: (value: any) => AnyTable; orderBy?: (value: any) => AnyTable; limit?: (value: number) => AnyTable };
const milliseconds = (value: unknown): number => value instanceof Date ? value.getTime() : Date.parse(String(value));

function markdown(report: any): string {
  const etaRows = Object.entries(report.eta.byHorizon as Record<string, any>).map(([bucket, value]) => `| ${bucket} | ${value.scoredFlights} | ${value.maeSeconds === null ? "—" : Math.round(value.maeSeconds)} | ${value.medianAbsoluteErrorSeconds === null ? "—" : Math.round(value.medianAbsoluteErrorSeconds)} | ${value.p90AbsoluteErrorSeconds === null ? "—" : Math.round(value.p90AbsoluteErrorSeconds)} | ${value.biasSeconds === null ? "—" : Math.round(value.biasSeconds)} |`).join("\n");
  const confidenceRows = Object.entries(report.eta.byConfidence as Record<string, any>).map(([confidence, value]) => `| ${confidence} | ${value.scoredFlights} | ${value.maeSeconds === null ? "—" : Math.round(value.maeSeconds)} | ${value.medianAbsoluteErrorSeconds === null ? "—" : Math.round(value.medianAbsoluteErrorSeconds)} | ${value.p90AbsoluteErrorSeconds === null ? "—" : Math.round(value.p90AbsoluteErrorSeconds)} |`).join("\n");
  return `# Predictive Prospective Validation V2\n\nGenerated: ${report.generatedAt}\nPeriod: ${report.period.from ?? "—"} – ${report.period.to ?? "—"}\nOverall status: **${report.overallStatus}**\n\n## Executive Summary\n\n- Flights: ${report.flights}\n- Observations: ${report.observations}\n- Scoreable ETA cases: ${report.eta.overall.scoredFlights}\n- Scoreable runway cases: ${report.runway.scoreableTruth}\n\n## ETA\n\n| Horizon | N | MAE (s) | Median (s) | P90 (s) | Bias (s) |\n|---|---:|---:|---:|---:|---:|\n${etaRows || "| — | 0 | — | — | — | — |"}\n\n### Confidence\n\n| Confidence | N | MAE (s) | Median (s) | P90 (s) |\n|---|---:|---:|---:|---:|\n${confidenceRows || "| — | 0 | — | — | — |"}\n\n## RUNWAY\n\n| Metric | Result |\n|---|---:|\n| Eligible arrivals | ${report.runway.eligibleArrivals} |\n| Predictions | ${report.runway.predictions} |\n| Scoreable truth | ${report.runway.scoreableTruth} |\n| Exact-end accuracy | ${report.runway.exactEndAccuracy === null ? "—" : `${(report.runway.exactEndAccuracy * 100).toFixed(1)}%`} |\n| Physical-runway accuracy | ${report.runway.physicalAccuracy === null ? "—" : `${(report.runway.physicalAccuracy * 100).toFixed(1)}%`} |\n| UNKNOWN prediction rate | ${(report.runway.unknownPredictionRate * 100).toFixed(1)}% |\n| Coverage | ${report.runway.coverage === null ? "—" : `${(report.runway.coverage * 100).toFixed(1)}%`} |\n\n## Ground Truth\n\n- CONFIRMED: ${report.groundTruth.CONFIRMED}\n- AMBIGUOUS: ${report.groundTruth.AMBIGUOUS}\n- UNKNOWN: ${report.groundTruth.UNKNOWN}\n- UNSCORABLE: ${report.groundTruth.UNSCORABLE}\n\n## Readiness\n\n- ETA: **${report.readiness.ETA}** (automatic graduation: NO)\n- RUNWAY: **${report.readiness.RUNWAY}** (automatic graduation: NO)\n\n## Data Quality / Health\n\n- Missing destination: ${report.dataQuality.missingDestination}\n- Missing runway geometry: ${report.dataQuality.missingRunwayGeometry}\n- Incomplete lifecycle matches: ${report.dataQuality.incompleteFlightLifecycle}\n- Persistence failures: ${report.health.persistenceFailures}\n- Dropped observations: ${report.health.droppedObservations}\n- Queue high-water mark: ${report.health.queueHighWaterMark}\n`;
}

const db = getPrisma();
if (!db) {
  const report = { generatedAt: new Date().toISOString(), overallStatus: "INSUFFICIENT_DATA", observations: 0, flights: 0, period: { from: null, to: null }, message: "Database is not configured; no live data was read." };
  await mkdir("artifacts", { recursive: true }); await writeFile(jsonPath, `${JSON.stringify(report, null, 2)}\n`); await writeFile(markdownPath, `# Predictive Prospective Validation V2\n\nStatus: **INSUFFICIENT_DATA**\n\nDatabase is not configured.\n`); console.log(`Wrote ${jsonPath} and ${markdownPath}`);
} else {
  const schema = db.orm.public as unknown as Record<string, AnyTable>;
  const observations = (await schema.PredictiveObservation.all()).slice(-MAX_OBSERVATIONS);
  const [flights, aircrafts, airports, runways] = await Promise.all([schema.Flight.all(), schema.Aircraft.all(), schema.Airport.all(), schema.AirportRunway.all()]);
  const aircraftIdByHex = new Map(aircrafts.map((aircraft) => [String(aircraft.icaoHex).toUpperCase(), aircraft.id]));
  const runwayByAirport = new Map<number, any[]>(); for (const runway of runways) { const list = runwayByAirport.get(runway.airportId) ?? []; if (list.length < 64) list.push(runway); runwayByAirport.set(runway.airportId, list); }
  const airportValues = airports.map((airport) => ({ icaoCode: airport.icao, iataCode: airport.iata, name: airport.name, city: airport.city, country: airport.country, latitude: airport.latitude, longitude: airport.longitude, elevationFt: airport.elevationFt }));
  const positionsByFlight = new Map<number, any[]>();
  for (const flight of flights) positionsByFlight.set(flight.id, await schema.FlightPosition.where({ flightId: flight.id }).all());
  const groundTruth = new Map<number, any>();
  for (const flight of flights) {
    const positions = positionsByFlight.get(flight.id) ?? [];
    const ground = classifyTerminalGroundTruth({ flightId: flight.id, positions: positions.map((position): TerminalTrackSample => ({ recordedAt: new Date(milliseconds(position.recordedAt)).toISOString(), lat: position.lat, lon: position.lon, altitudeFt: position.altitude, groundSpeedKt: position.groundSpeed, trackDeg: position.track, verticalRateFpm: position.verticalRate, onGround: null })), airports: airportValues, runwaysByAirport: new Map(airportValues.map((airport) => [airport.icaoCode, runwayByAirport.get(airports.find((item) => item.icao === airport.icaoCode)?.id ?? -1) ?? []])) });
    groundTruth.set(flight.id, ground);
  }
  const flightFor = (observation: any): any | null => flights.filter((flight) => flight.aircraftId === aircraftIdByHex.get(String(observation.aircraftIcao).toUpperCase()) || flight.id === observation.flightId).filter((flight) => { const at = milliseconds(observation.predictedAt); return at >= milliseconds(flight.startTime) && at <= milliseconds(flight.endTime ?? flight.lastSeenAt) + 180_000; }).sort((a, b) => Math.abs(milliseconds(a.startTime) - milliseconds(observation.predictedAt)) - Math.abs(milliseconds(b.startTime) - milliseconds(observation.predictedAt)))[0] ?? null;
  const etaResults: EtaValidationResult[] = []; const byHorizon = new Map<string, EtaValidationResult[]>(); const byConfidence = new Map<string, EtaValidationResult[]>(); const runwayResults: RunwayValidationResult[] = []; const gtCounts: Record<string, number> = { CONFIRMED: 0, AMBIGUOUS: 0, UNKNOWN: 0, UNSCORABLE: 0 }; let from = Number.POSITIVE_INFINITY; let to = 0; let eligibleArrivals = 0; let runwayPredictions = 0; let unknownPredictions = 0; let exact = 0; let physical = 0;
  for (const observation of observations) {
    const at = milliseconds(observation.predictedAt); from = Math.min(from, at); to = Math.max(to, at); const flight = flightFor(observation); const truth = flight ? groundTruth.get(flight.id) : null; const status: GroundTruthStatus = truth?.status ?? "UNKNOWN"; gtCounts[status] = (gtCounts[status] ?? 0) + 1;
    if (observation.capability === "ETA") { const result = scoreEta(observation.predictedLandingAt ? milliseconds(observation.predictedLandingAt) : null, truth?.landingAt ? milliseconds(truth.landingAt) : null, status); etaResults.push(result); (byHorizon.get(observation.horizonBucket) ?? (byHorizon.set(observation.horizonBucket, []), byHorizon.get(observation.horizonBucket)!)).push(result); (byConfidence.get(observation.etaConfidence ?? observation.predictionConfidence) ?? (byConfidence.set(observation.etaConfidence ?? observation.predictionConfidence, []), byConfidence.get(observation.etaConfidence ?? observation.predictionConfidence)!)).push(result); }
    if (observation.capability === "RUNWAY") { eligibleArrivals += 1; runwayPredictions += observation.predictedRunway ? 1 : 0; unknownPredictions += observation.predictedRunway ? 0 : 1; const result = scoreRunway(observation.predictedRunway, truth?.runway, truth?.runwayStatus === "CONFIRMED" ? "CONFIRMED" : status); runwayResults.push(result); exact += result.exactEnd ? 1 : 0; physical += result.physicalRunway ? 1 : 0; }
  }
  const etaOverall = summarizeEta(etaResults); const summarizeMap = (map: Map<string, EtaValidationResult[]>) => Object.fromEntries([...map.entries()].map(([key, values]) => [key, summarizeEta(values)])); const scoreableRunway = runwayResults.filter((result) => result.status === "SCORED").length; const report = { generatedAt: new Date().toISOString(), period: { from: Number.isFinite(from) ? new Date(from).toISOString() : null, to: to ? new Date(to).toISOString() : null }, observations: observations.length, flights: flights.length, overallStatus: etaOverall.scoredFlights || scoreableRunway ? "READY_FOR_EVIDENCE" : "INSUFFICIENT_DATA", eta: { overall: etaOverall, byHorizon: summarizeMap(byHorizon), byConfidence: summarizeMap(byConfidence) }, runway: { eligibleArrivals, predictions: runwayPredictions, scoreableTruth: scoreableRunway, exactEndAccuracy: scoreableRunway ? exact / scoreableRunway : null, physicalAccuracy: scoreableRunway ? physical / scoreableRunway : null, unknownPredictionRate: eligibleArrivals ? unknownPredictions / eligibleArrivals : 0, coverage: eligibleArrivals ? scoreableRunway / eligibleArrivals : null }, groundTruth: { ...gtCounts, UNSCORABLE: observations.length - gtCounts.CONFIRMED - gtCounts.AMBIGUOUS - gtCounts.UNKNOWN }, readiness: { ETA: etaOverall.scoredFlights >= 100 && etaResults.length >= 30 ? "CANDIDATE" : "INSUFFICIENT_DATA", RUNWAY: scoreableRunway >= 100 ? "CANDIDATE" : "INSUFFICIENT_DATA" }, dataQuality: { missingDestination: observations.filter((item) => !item.destinationIcao).length, missingRunwayGeometry: observations.filter((item) => item.capability === "RUNWAY" && !item.predictedRunway).length, incompleteFlightLifecycle: observations.filter((item) => !flightFor(item)).length }, health: { persistenceFailures: null, droppedObservations: null, queueHighWaterMark: null } };
  await mkdir("artifacts", { recursive: true }); await writeFile(jsonPath, `${JSON.stringify(report, null, 2)}\n`); await writeFile(markdownPath, `${markdown(report)}\n`); console.log(`Wrote ${jsonPath} and ${markdownPath}`);
}
