import { mkdir, writeFile } from "node:fs/promises";
import pg from "pg";
import { classifyTerminalGroundTruth, type TerminalTrackSample } from "@/lib/predictive-intelligence/terminal-ground-truth";
import { scoreEta, scoreRunway, summarizeEta, type EtaValidationResult, type GroundTruthStatus, type RunwayValidationResult } from "@/lib/predictive-intelligence/validation";

const jsonPath = process.env.PREDICTIVE_PROSPECTIVE_JSON ?? "artifacts/predictive-validation-prospective-v2.json";
const markdownPath = process.env.PREDICTIVE_PROSPECTIVE_MARKDOWN ?? "artifacts/predictive-validation-prospective-v2.md";
const BATCH_SIZE = 500;
const MAX_OBSERVATIONS = 50_000;
const MAX_POSITIONS_PER_FLIGHT = 512;
const DEFAULT_WINDOW_MS = 30 * 24 * 60 * 60_000;

type Observation = { observationKey: string; aircraftIcao: string; flightId: number | null; destinationIcao: string | null; predictedAt: Date; predictedAtText: string; horizonBucket: string; predictedLandingAt: Date | null; predictedRunway: string | null; predictionConfidence: string; etaConfidence: string | null; capability: string };
type Flight = { id: number; aircraftIcao: string; startTime: Date; endTime: Date | null; lastSeenAt: Date; origin: string | null; destination: string | null };
type Position = { flightId: number; recordedAt: Date; lat: number; lon: number; altitude: number | null; groundSpeed: number | null; track: number | null; verticalRate: number | null };
type Airport = { id: number; icao: string; iata: string | null; name: string; city: string | null; country: string | null; latitude: number; longitude: number; elevationFt: number | null };
type Runway = { airportId: number; sourceAirportIdent: string; leIdent: string | null; leLatitude: number | null; leLongitude: number | null; leElevationFt: number | null; leHeadingDegT: number | null; heIdent: string | null; heLatitude: number | null; heLongitude: number | null; heElevationFt: number | null; heHeadingDegT: number | null };

const parseDate = (value: string | undefined, fallback: Date): Date => { if (!value) return fallback; const parsed = new Date(value); if (!Number.isFinite(parsed.getTime())) throw new Error(`Invalid report window timestamp: ${value}`); return parsed; };
const iso = (value: Date | null): string | null => value?.toISOString() ?? null;
const emptySummary = () => summarizeEta([]);

type EtaSummary = ReturnType<typeof summarizeEta>;
type Report = {
  generatedAt: string; window: { from: string; to: string }; period: { from: string | null; to: string | null }; overallStatus: "READY_FOR_EVIDENCE" | "INSUFFICIENT_DATA"; observations: number; flights: number;
  eta: { overall: EtaSummary; byHorizon: Record<string, EtaSummary>; byConfidence: Record<string, EtaSummary> };
  runway: { eligibleArrivals: number; predictions: number; scoreableTruth: number; exactEndAccuracy: number | null; physicalAccuracy: number | null; unknownPredictionRate: number; coverage: number | null };
  groundTruth: Record<GroundTruthStatus | "UNSCORABLE", number>; readiness: { ETA: string; RUNWAY: string };
  dataQuality: { missingDestination: number; missingRunwayGeometry: number; incompleteFlightLifecycle: number };
  health: { persistenceFailures: null; droppedObservations: null; queueHighWaterMark: null; queryBatches: number; maxPositionsPerFlight: number };
};

function emptyReport(from: Date, to: Date): Report {
  return { generatedAt: new Date().toISOString(), window: { from: from.toISOString(), to: to.toISOString() }, period: { from: null, to: null }, overallStatus: "INSUFFICIENT_DATA", observations: 0, flights: 0, eta: { overall: emptySummary(), byHorizon: {}, byConfidence: {} }, runway: { eligibleArrivals: 0, predictions: 0, scoreableTruth: 0, exactEndAccuracy: null, physicalAccuracy: null, unknownPredictionRate: 0, coverage: null }, groundTruth: { CONFIRMED: 0, AMBIGUOUS: 0, UNKNOWN: 0, UNSCORABLE: 0 }, readiness: { ETA: "INSUFFICIENT_DATA", RUNWAY: "INSUFFICIENT_DATA" }, dataQuality: { missingDestination: 0, missingRunwayGeometry: 0, incompleteFlightLifecycle: 0 }, health: { persistenceFailures: null, droppedObservations: null, queueHighWaterMark: null, queryBatches: 0, maxPositionsPerFlight: MAX_POSITIONS_PER_FLIGHT } };
}

function markdown(report: Report): string {
  const etaRows = Object.entries(report.eta.byHorizon).map(([bucket, value]) => `| ${bucket} | ${value.scoredFlights} | ${value.maeSeconds === null ? "—" : Math.round(value.maeSeconds)} | ${value.medianAbsoluteErrorSeconds === null ? "—" : Math.round(value.medianAbsoluteErrorSeconds)} | ${value.p90AbsoluteErrorSeconds === null ? "—" : Math.round(value.p90AbsoluteErrorSeconds)} | ${value.biasSeconds === null ? "—" : Math.round(value.biasSeconds)} |`).join("\n");
  const confidenceRows = Object.entries(report.eta.byConfidence).map(([confidence, value]) => `| ${confidence} | ${value.scoredFlights} | ${value.maeSeconds === null ? "—" : Math.round(value.maeSeconds)} | ${value.medianAbsoluteErrorSeconds === null ? "—" : Math.round(value.medianAbsoluteErrorSeconds)} | ${value.p90AbsoluteErrorSeconds === null ? "—" : Math.round(value.p90AbsoluteErrorSeconds)} |`).join("\n");
  return `# Predictive Prospective Validation V2\n\nGenerated: ${report.generatedAt}\nWindow: ${report.window.from} – ${report.window.to}\nObserved period: ${report.period.from ?? "—"} – ${report.period.to ?? "—"}\nOverall status: **${report.overallStatus}**\n\n- Flights matched: ${report.flights}\n- Observations: ${report.observations}\n- Query batches: ${report.health.queryBatches}\n\n## ETA\n\n| Horizon | N | MAE (s) | Median (s) | P90 (s) | Bias (s) |\n|---|---:|---:|---:|---:|---:|\n${etaRows || "| — | 0 | — | — | — | — |"}\n\n### Confidence\n\n| Confidence | N | MAE (s) | Median (s) | P90 (s) |\n|---|---:|---:|---:|---:|\n${confidenceRows || "| — | 0 | — | — | — |"}\n\n## RUNWAY\n\n| Metric | Result |\n|---|---:|\n| Eligible arrivals | ${report.runway.eligibleArrivals} |\n| Predictions | ${report.runway.predictions} |\n| Scoreable truth | ${report.runway.scoreableTruth} |\n| Exact-end accuracy | ${report.runway.exactEndAccuracy === null ? "—" : `${(report.runway.exactEndAccuracy * 100).toFixed(1)}%`} |\n| Physical-runway accuracy | ${report.runway.physicalAccuracy === null ? "—" : `${(report.runway.physicalAccuracy * 100).toFixed(1)}%`} |\n| UNKNOWN prediction rate | ${(report.runway.unknownPredictionRate * 100).toFixed(1)}% |\n| Coverage | ${report.runway.coverage === null ? "—" : `${(report.runway.coverage * 100).toFixed(1)}%`} |\n\n## Ground Truth\n\n- CONFIRMED: ${report.groundTruth.CONFIRMED}\n- AMBIGUOUS: ${report.groundTruth.AMBIGUOUS}\n- UNKNOWN: ${report.groundTruth.UNKNOWN}\n- UNSCORABLE: ${report.groundTruth.UNSCORABLE}\n\n## Readiness\n\n- ETA: **${report.readiness.ETA}** (automatic graduation: NO)\n- RUNWAY: **${report.readiness.RUNWAY}** (automatic graduation: NO)\n\n## Health\n\n- Persistence failures: ${report.health.persistenceFailures}\n- Max positions per flight: ${report.health.maxPositionsPerFlight}\n`;
}

async function run(): Promise<Report> {
  const to = parseDate(process.env.PREDICTIVE_PROSPECTIVE_TO, new Date()); const from = parseDate(process.env.PREDICTIVE_PROSPECTIVE_FROM, new Date(to.getTime() - DEFAULT_WINDOW_MS));
  if (!process.env.DATABASE_URL) return emptyReport(from, to);
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL, max: 1, statement_timeout: 60_000 });
  const etaResults: EtaValidationResult[] = []; const byHorizon = new Map<string, EtaValidationResult[]>(); const byConfidence = new Map<string, EtaValidationResult[]>(); const runwayResults: RunwayValidationResult[] = []; const flightIds = new Set<number>();
  const gtCounts: Record<GroundTruthStatus | "UNSCORABLE", number> = { CONFIRMED: 0, AMBIGUOUS: 0, UNKNOWN: 0, UNSCORABLE: 0 };
  let cursorAt = from.toISOString(); let cursorKey = ""; let observations = 0; let periodFrom: Date | null = null; let periodTo: Date | null = null; let batches = 0; let eligibleArrivals = 0; let runwayPredictions = 0; let unknownPredictions = 0; let exact = 0; let physical = 0; let missingDestination = 0; let missingRunwayGeometry = 0; let incompleteFlightLifecycle = 0;
  try {
    while (observations < MAX_OBSERVATIONS) {
      const limit = Math.min(BATCH_SIZE, MAX_OBSERVATIONS - observations);
      const rows = (await pool.query<Observation>(`SELECT "observationKey","aircraftIcao","flightId","destinationIcao","predictedAt","predictedAt"::text AS "predictedAtText","horizonBucket","predictedLandingAt","predictedRunway","predictionConfidence","etaConfidence","capability" FROM public."predictiveObservation" WHERE "predictedAt" >= $1 AND "predictedAt" < $2 AND ("predictedAt" > $3::timestamptz OR ("predictedAt" = $3::timestamptz AND "observationKey" > $4)) ORDER BY "predictedAt","observationKey" LIMIT ${limit}`, [from, to, cursorAt, cursorKey])).rows;
      if (!rows.length) break;
      batches += 1; observations += rows.length; cursorAt = rows.at(-1)!.predictedAtText; cursorKey = rows.at(-1)!.observationKey;
      for (const row of rows) { periodFrom = periodFrom === null || row.predictedAt.getTime() < periodFrom.getTime() ? row.predictedAt : periodFrom; periodTo = periodTo === null || row.predictedAt.getTime() > periodTo.getTime() ? row.predictedAt : periodTo; if (!row.destinationIcao) missingDestination += 1; }
      const ids = [...new Set(rows.map((row) => row.flightId).filter((id): id is number => Number.isInteger(id)))];
      const candidates = ids.length === 0 ? [] : (await pool.query<Flight>(`SELECT f.id,a."icaoHex" AS "aircraftIcao",f."startTime",f."endTime",f."lastSeenAt",f."origin",f."destination" FROM public."flight" f JOIN public."aircraft" a ON a.id=f."aircraftId" WHERE f.id = ANY($1::int[]) AND f."startTime" < $2 AND coalesce(f."endTime",f."lastSeenAt") >= $3`, [ids, to, from])).rows;
      const candidateIds = [...new Set(candidates.map((flight) => flight.id))]; candidateIds.forEach((id) => flightIds.add(id));
      const positions = candidateIds.length === 0 ? [] : (await pool.query<Position>(`SELECT "flightId","recordedAt",lat,lon,altitude,"groundSpeed",track,"verticalRate" FROM (SELECT p.*,row_number() OVER (PARTITION BY "flightId" ORDER BY "recordedAt" DESC,id DESC) AS rn FROM public."flightPosition" p WHERE "flightId" = ANY($1::int[])) bounded WHERE rn <= ${MAX_POSITIONS_PER_FLIGHT} ORDER BY "flightId","recordedAt",id`, [candidateIds])).rows;
      const positionsByFlight = new Map<number, Position[]>(); for (const position of positions) positionsByFlight.set(position.flightId, [...(positionsByFlight.get(position.flightId) ?? []), position]);
      const codes = [...new Set(candidates.flatMap((flight) => [flight.origin, flight.destination]).filter((code): code is string => Boolean(code)).map((code) => code.toUpperCase()))];
      const airports = codes.length ? (await pool.query<Airport>(`SELECT id,icao,iata,name,city,country,latitude,longitude,"elevationFt" FROM public."airport" WHERE upper(icao) = ANY($1::text[]) OR upper(coalesce(iata,'')) = ANY($1::text[])`, [codes])).rows : [];
      const airportByCode = new Map<string, Airport>(); for (const airport of airports) { airportByCode.set(airport.icao.toUpperCase(), airport); if (airport.iata) airportByCode.set(airport.iata.toUpperCase(), airport); }
      const airportIds = airports.map((airport) => airport.id); const runwayRows = airportIds.length ? (await pool.query<Runway>(`SELECT "airportId","sourceAirportIdent","leIdent","leLatitude","leLongitude","leElevationFt","leHeadingDegT","heIdent","heLatitude","heLongitude","heElevationFt","heHeadingDegT" FROM public."airportRunway" WHERE "airportId" = ANY($1::int[])`, [airportIds])).rows : [];
      const runwaysByAirport = new Map<string, Runway[]>(); for (const runway of runwayRows) { const airport = airports.find((item) => item.id === runway.airportId); if (airport) runwaysByAirport.set(airport.icao.toUpperCase(), [...(runwaysByAirport.get(airport.icao.toUpperCase()) ?? []), runway]); }
      const truthByFlight = new Map<number, ReturnType<typeof classifyTerminalGroundTruth>>();
      for (const flight of candidates) { const destination = flight.destination ? airportByCode.get(flight.destination.toUpperCase()) : undefined; truthByFlight.set(flight.id, classifyTerminalGroundTruth({ flightId: flight.id, positions: (positionsByFlight.get(flight.id) ?? []).map((position): TerminalTrackSample => ({ recordedAt: position.recordedAt.toISOString(), lat: position.lat, lon: position.lon, altitudeFt: position.altitude, groundSpeedKt: position.groundSpeed, trackDeg: position.track, verticalRateFpm: position.verticalRate, onGround: null })), airports: destination ? [{ icaoCode: destination.icao, iataCode: destination.iata, name: destination.name, city: destination.city, country: destination.country, latitude: destination.latitude, longitude: destination.longitude, elevationFt: destination.elevationFt }] : [], runwaysByAirport: destination ? new Map([[destination.icao, runwaysByAirport.get(destination.icao.toUpperCase()) ?? []]]) : new Map() })); }
      for (const observation of rows) {
        const flight = candidates.find((candidate) => candidate.id === observation.flightId || (candidate.aircraftIcao.toUpperCase() === observation.aircraftIcao.toUpperCase() && observation.predictedAt >= candidate.startTime && observation.predictedAt <= new Date((candidate.endTime ?? candidate.lastSeenAt).getTime() + 180_000))); const truth = flight ? truthByFlight.get(flight.id) : null; const status: GroundTruthStatus = truth?.status ?? "UNKNOWN"; gtCounts[status] += 1; if (!flight) incompleteFlightLifecycle += 1;
        if (observation.capability === "ETA") { const result = scoreEta(observation.predictedLandingAt ? observation.predictedLandingAt.getTime() : null, truth?.landingAt ? Date.parse(truth.landingAt) : null, status); etaResults.push(result); (byHorizon.get(observation.horizonBucket) ?? (byHorizon.set(observation.horizonBucket, []), byHorizon.get(observation.horizonBucket)!)).push(result); const confidence = observation.etaConfidence ?? observation.predictionConfidence; (byConfidence.get(confidence) ?? (byConfidence.set(confidence, []), byConfidence.get(confidence)!)).push(result); }
        if (observation.capability === "RUNWAY") { eligibleArrivals += 1; runwayPredictions += observation.predictedRunway ? 1 : 0; unknownPredictions += observation.predictedRunway ? 0 : 1; const result = scoreRunway(observation.predictedRunway, truth?.runway ?? null, truth?.runwayStatus === "CONFIRMED" ? "CONFIRMED" : status); runwayResults.push(result); exact += result.exactEnd ? 1 : 0; physical += result.physicalRunway ? 1 : 0; if (!observation.predictedRunway) missingRunwayGeometry += 1; }
      }
    }
  } finally { await pool.end(); }
  const etaOverall = summarizeEta(etaResults); const summarizeMap = (map: Map<string, EtaValidationResult[]>) => Object.fromEntries([...map.entries()].map(([key, values]) => [key, summarizeEta(values)])); const scoreableRunway = runwayResults.filter((result) => result.status === "SCORED").length; const minimumDescriptiveSample = 30;
  return { generatedAt: new Date().toISOString(), window: { from: from.toISOString(), to: to.toISOString() }, period: { from: iso(periodFrom), to: iso(periodTo) }, observations, flights: flightIds.size, overallStatus: etaOverall.scoredFlights >= minimumDescriptiveSample || scoreableRunway >= minimumDescriptiveSample ? "READY_FOR_EVIDENCE" : "INSUFFICIENT_DATA", eta: { overall: etaOverall, byHorizon: summarizeMap(byHorizon), byConfidence: summarizeMap(byConfidence) }, runway: { eligibleArrivals, predictions: runwayPredictions, scoreableTruth: scoreableRunway, exactEndAccuracy: scoreableRunway >= minimumDescriptiveSample ? exact / scoreableRunway : null, physicalAccuracy: scoreableRunway >= minimumDescriptiveSample ? physical / scoreableRunway : null, unknownPredictionRate: eligibleArrivals ? unknownPredictions / eligibleArrivals : 0, coverage: eligibleArrivals >= minimumDescriptiveSample ? scoreableRunway / eligibleArrivals : null }, groundTruth: { ...gtCounts }, readiness: { ETA: etaOverall.scoredFlights >= 100 && etaResults.length >= 30 ? "CANDIDATE" : "INSUFFICIENT_DATA", RUNWAY: scoreableRunway >= 100 ? "CANDIDATE" : "INSUFFICIENT_DATA" }, dataQuality: { missingDestination, missingRunwayGeometry, incompleteFlightLifecycle }, health: { persistenceFailures: null, droppedObservations: null, queueHighWaterMark: null, queryBatches: batches, maxPositionsPerFlight: MAX_POSITIONS_PER_FLIGHT } };
}

const report = await run(); await mkdir("artifacts", { recursive: true }); await writeFile(jsonPath, `${JSON.stringify(report, null, 2)}\n`); await writeFile(markdownPath, `${markdown(report)}\n`); console.log(JSON.stringify({ jsonPath, markdownPath, overallStatus: report.overallStatus, observations: report.observations, scoreableEta: report.eta.overall.scoredFlights, scoreableRunway: report.runway.scoreableTruth, queryBatches: report.health.queryBatches }, null, 2));
